In [1]:
import numpy as np

1.Create a null vector of size 10 but the fifth value which is 1.

In [8]:
ar=np.zeros(10,dtype=np.int32)
ar[4]=1
ar

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2. Create a vector with values ranging from 10 to 49.

In [10]:
ar1=np.arange(10,49)
ar1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
ar2=np.arange(9).reshape(3,3)
ar2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [24]:
ar3=np.nonzero([1,2,0,0,4,0])
ar3

(array([0, 1, 4], dtype=int64),)

5. Create a 10x10 array with random values and find the minimum and maximum values.

In [31]:
arr4=np.random.random((10,10))

mi,ma=arr4.min(),arr4.max()

print('min=',mi)
print('max=',ma)


min= 0.029445499844618084
max= 0.997393894135297


6. Create a random vector of size 30 and find the mean value.

In [32]:
arr5=np.random.random(30)
m=arr5.mean()
print(m)

0.4734455081077317
